/*
 * Copyright 2021 <a href="mailto:dev@aeonsvirtue.com">Aeon's Virtue (K. Geltmeier)</a>.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * Version v. 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * If a copy of the MPL was not distributed with this file, you can obtain one
 * at
 *
 *      https://mozilla.org/MPL/2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.aeonsvirtue.fontviewer;

import java.awt.Font;

/**
 *
 * @author <a href="mailto:dev@aeonsvirtue.com">Aeon's Virtue (K. Geltmeier)</a>
 */
public class FontItem extends javax.swing.JPanel {    
    /**
     * Creates new form FontItem
     * @param font
     * @param text
     */
    public FontItem(Font font, String[] text) {
        initComponents();
        lblFontname.setText(font.getFontName());
        lblText.setFont(font);        
        setText(text);
    }
    
    @Override
    public void setFont(Font font) {
        super.setFont(font);
        if (lblFontname != null) lblFontname.setText(font.getFontName());
        if (lblText != null) lblText.setFont(font);
    }
    private void setText(String[] text) {
        lblText.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFontname = new javax.swing.JLabel();
        lblText = new com.aeonsvirtue.fontviewer.Label();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFontname.setText(" ");

        lblText.setBackground(new java.awt.Color(250, 250, 250));
        lblText.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFontname, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
            .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFontname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFontname;
    private com.aeonsvirtue.fontviewer.Label lblText;
    // End of variables declaration//GEN-END:variables
}
